name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*' 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Get version (from git tag or fallback)
        id: vars
        run: |
          VERSION=$(git describe --tags --always --dirty || echo "0.0.0")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build binary
        run: |
          mkdir -p bin
          go build -o bin/server main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-${{ steps.vars.outputs.version }}-linux-amd64
          path: bin/server
